FROM jupyter/base-notebook

ARG  irods_gid=999
ENV  IRODS_GID ${irods_gid}

USER root

RUN apt-get update && apt-get install -y vim less

RUN groupadd -g $IRODS_GID irods && usermod -aG irods jovyan 

ADD lpfilter.ipynb /home/jovyan/work/.

COPY mymodule/ /home/jovyan/work/mymodule/

RUN chown jovyan.users /home/jovyan/work/lpfilter.ipynb

COPY mymodule/ /home/jovyan/work/mymodule

RUN chown -R jovyan.users /home/jovyan/work/mymodule

USER jovyan

RUN conda init

RUN conda install -y -c conda-forge matplotlib numpy

RUN jupyter trust /home/jovyan/work/lpfilter.ipynb

CMD [ '/bin/bash' ]
